<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<!-- Datos especificos -->
	<xs:complexType name="DatosEspecificos">
		<xs:choice>
			<xs:element ref="Consulta"/>
			<xs:element ref="Retorno"/>
		</xs:choice>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<!-- Consulta -->
	<xs:element name="Consulta">
		<xs:annotation>
			<xs:documentation>Datos de consulta para servicio de consulta de plantilal media</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="FechaDesde" type="Fecha">
					<xs:annotation>
						<xs:documentation>Periodo a consultar - Fecha desde</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="FechaHasta" type="Fecha">
					<xs:annotation>
						<xs:documentation>Periodo a consultar - Fecha hasta</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<!-- Retorno de datos especificos -->
	<xs:element name="Retorno">
		<xs:annotation>
			<xs:documentation>Datos de retorno para servicio de consulta de plantilal media</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="Estado"/>
				<xs:element ref="Resultado" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Codigo de estado de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:annotation>
			<xs:documentation>Codigo de estado secundario de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:annotation>
			<xs:documentation>Descripcion del estado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Resultado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="RazonSocial" minOccurs="0"/>
				<xs:element ref="Trabajadores" minOccurs="0"/>
				<xs:element name="FechaProceso" type="Fecha" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Fecha en la que se realizó el proceso</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="CCC" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Fecha">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:element name="Trabajadores">
		<xs:annotation>
			<xs:documentation>Número Medio de Trabajadores.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RazonSocial">
		<xs:annotation>
			<xs:documentation>Razon Social consultada.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="55"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CCC">
		<xs:annotation>
			<xs:documentation>Código de Cuenta de Cotización principal</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
